### ISSUE TITLE
Installation instructions incomplete

### ISSUE THREAD

**Issue by mint-ws** [railsware/mailtrap-php#18]
From the readme:

If you just want to get started quickly you should run one of the following command (depends on which HTTP client you want to use):

`# With symfony http client (recommend)`
`composer require railsware/mailtrap-php symfony/http-client nyholm/psr7`

Produces the following error:
`Unable to send message with the "Mailtrap\Bridge\Transport\MailtrapApiTransport" transport: No HTTPlug clients found.`

`# This removes the error but I have no idea if it's the right thing to do.`
`composer require railsware/mailtrap-php symfony/http-client nyholm/psr7  php-http/guzzle7-adapter`

**Comment by gaalferov** [comment]
Hi @mint-ws
Can you share more information about your environment?
What PHP version do you use?
What Symfony version?
What version of the Mailtrap library do you use? (latest or not)

**Comment by mint-ws** [comment]
Hi @gaalferov 
This is my local dev environment:

`
Laravel Version: 10.39.0
`
`
PHP Version: 8.2.6
`
`
Mailtrap version: "railsware/mailtrap-php": "^1.7"
`

Hope that helps, let me know if you need more info.
Thanks

**Comment by gaalferov** [comment]
@mint-ws Looks like you are using the `1.7.1` version. Try to update `railsware/mailtrap-php` package to the latest version, because in the last version [1.7.2](https://github.com/railsware/mailtrap-php/releases/tag/1.7.2) I added the required package to prevent this issue
```
composer update railsware/mailtrap-php
