### ISSUE TITLE
Laravel 11 compatibility

### ISSUE THREAD

**Issue by hempsworth** [railsware/mailtrap-php#20]
Laravel 11 depends on `"symfony/mime": ^7.0` however the Mailtrap package currently only supports `^5.0|^6.0`.

I have only very briefly tested a fork updating to `^7.0` which seems to work as expected with only some type setting needed.

https://github.com/railsware/mailtrap-php/compare/main...hempsworth:mailtrap-php:main

It will need more testing, but hopefully, this helps somebody upgrading to Laravel 11!

**Comment by gaalferov** [comment]
@hempsworth Thank you for the feedback.
We will check and release a new release soon
